stages:
  - build
  - deploy

build:
  stage: build
  script: "./build.sh"
  tags:
    - linux
  artifacts:
    paths:
      - 'armstrong-react/dist'

deploy:
  stage: deploy
  script: "./deploy.sh"
  tags:
    - linux
  only:
    - master
  when: manual
  dependencies:
    - build
