stages:
  - build
  - deploy
  - pages

build:
  stage: build
  script: "./build.sh"
  tags:
    - linux
  artifacts:
    paths:
      - 'armstrong-react/dist'

deploy:
  stage: deploy
  script: "./deploy.sh"
  tags:
    - linux
  only:
    - master
  when: manual
  dependencies:
    - build

pages:
  stage: pages
  script:
  - "./build-docs.sh"
  - "cp -r docs/www public"
  tags:
    - linux
  when: manual
  artifacts:
    paths:
    - public
