variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy
  - pages

build:
  stage: build
  script: "./build.sh"
  tags:
    - linux
  artifacts:
    paths:
      - "armstrong-react/dist"

pages:
  image: node:10.15.3-alpine
  stage: pages
  tags:
    - docker
  script: "./build-storybook.sh"
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  script: "./deploy.sh"
  tags:
    - linux
  only:
    - master
  dependencies:
    - build
# pages:
#   stage: pages
#   script:
#   - "./build-docs.sh"
#   - "cp -r docs/www public"
#   tags:
#     - linux
#   when: manual
#   artifacts:
#     paths:
#     - public
