stages:
  - build
  - deploy
  - storybook

build:
  stage: build
  script: "./build.sh"
  tags:
    - linux
  artifacts:
    paths:
      - "armstrong-react/dist"

storybook:
  stage: storybook
  script:
    - cd storybook
    - npm i
    - npm run build

deploy:
  stage: deploy
  script: "./deploy.sh"
  tags:
    - linux
  only:
    - master
  dependencies:
    - build
# pages:
#   stage: pages
#   script:
#   - "./build-docs.sh"
#   - "cp -r docs/www public"
#   tags:
#     - linux
#   when: manual
#   artifacts:
#     paths:
#     - public
