variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy
  - pages

build:
  image: node:10.15.3-alpine
  stage: build
  tags:
    - docker
  script:
    - "cd armstrong-react"
    - "npm i"
    - "npm run build"
  artifacts:
    paths:
      - "armstrong-react/dist"

pages:
  image: node:10.15.3-alpine
  stage: pages
  tags:
    - docker
  script:
    - "cd armstrong-react"
    - "npm i"
    - "cd ../storybook"
    - "npm i"
    - "node ./symlink.js"
    - "npm run build"
  artifacts:
    paths:
      - public

deploy:
  image: node:10.15.3-alpine
  stage: deploy
  tags:
    - docker
  only:
    - master
  script: "npm publish"
  dependencies:
    - build
