name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:10.15.3-alpine

    steps:
      - uses: actions/checkout@master

      - name: Publish
        run: cd armstrong-react && npm i && npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
